### ISSUE TITLE
No settings menu & alt-u doesn't do anything. 

### ISSUE THREAD

**Issue by srki80** [ThomasGoris/CheckMate#4]
Hi,

I have installed CheckMate plugin on Intellij IDEA 2016.3.4 for Mac and I'm experiencing two issues. 

In the instructions you note that there is a settings menu that can be used to customize the search:
<em>Customize the search process through the settings menu (Ctrl+Alt+S: find CheckMate).</em>
CheckMate is found only under the plugins menu. I don't see any settings menu. 

You also note that Alt+U can be used to discover unchecked exceptions.
<em>Alt+U to discover unchecked exceptions that might be thrown in the statements you selected.</em>
This key shortcut doesn't do anything for me. If I do it in the editor it inserts an umlaut character (¨).

Is this a bug, or I'm doing something wrong?

Thanks.

**Comment by ThomasGoris** [comment]
I can reproduce the settings bug, a quick search indicates a change in intellij 2016. 
I'll look into it. 

I can't reproduce the ALT+U bug on windows, I'll try to get my hands on a Mac to test it.

**Comment by ThomasGoris** [comment]
I updated the plugin settings for IJ 2016 compatibility. 
The new version has been uploaded, but is pending for approval. 

Let me know if the update fixed your problems.

**Comment by ThomasGoris** [comment]
The update has been approved today. 
You can test the fix.

**Comment by srki80** [comment]
The settings menu is now showing. The alt-u still doesn't work on Mac OS X. Should I create a separate issue for this? Let me know if there's any way I can help since I have access to Mac.

**Comment by ThomasGoris** [comment]
Thanks for your quick response and offer to help. 
Please do create a different issue for the Mac OS X. 

I'm expecting a Mac from a friend this evening so I can start working on that. 
I will keep you up-to-date on the progress inside the new issue.
